---
logging:
  level:
    root: ERROR
    com.toanknguyen.optionsetl: INFO
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
optionsetl:
  test: testvalue
...
