---
logging:
  level:
    root: ERROR
    com.toanknguyen.optionsetl: DEBUG
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
optionsetl:
  source:
    directory: .
    pattern: '*.csv'
...
